services:
  - type: web
    name: salsabil-rh
    env: python
    buildCommand: bash build.sh
    startCommand: gunicorn -c gunicorn_config.py app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: SECRET_KEY
        value: b61a18f9ef47065d7cf7d69431e48771
      - key: FLASK_ENV
        value: production
      - key: DEBUG
        value: False
      - key: DATABASE_URL
        value: postgresql://db_salsabil_zxno_user:YMChtUjDA2lcWo4pyQwU58LTz17GIRLS@dpg-d441ukumcj7s73bjgo5g-a.oregon-postgres.render.com/db_salsabil_zxno
    autoDeploy: true
